name: Check Template Format

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/checkTemplate.yml'
      - '047-Dapr/**'
  
jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print Directory Structure
        run: |
           ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      - name: Template Format Check
        uses: jordanbean-msft/github-action-wth-template-check@v0.0.1
        with:
          inputPath: ${{ github.workspace }}/047-Dapr